name: geopoint_sql
description: Sql operations for geospatial data. Admin view for geopoint and geoserie.


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geopoint: ^1.0.0
  sqlcool:
    git:
      url: https://github.com/killerm250m/sqlcool.git
  sqlview:
    git:
      url: https://github.com/killerm250m/sqlview.git
  pedantic: ^1.7.0
  extra_pedantic: ^1.1.1+3



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

